---
- name: Update All Packages to latest [APT]
  hosts: all
  gather_facts: false
  become: true
  serial: 1
  vars:
    package: "*"
    apt_update_cache: true
    apt_clean: true
    apt_autoremove: true
  tasks:
    - name: Update package to latest version
      ansible.builtin.apt:
        name: "{{ package }}"
        state: latest
        update_cache: "{{ apt_update_cache }}"
        clean: "{{ apt_clean }}"
        autoremove: "{{ apt_autoremove }}"

    # Restart required?
    - name: Check if reboot is needed
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: check_reboot

    # Initate system restart
    - name: Reboot system
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible due to system updates"
        pre_reboot_delay: 15
        post_reboot_delay: 300
        reboot_timeout: 900
      when: check_reboot.stat.exists
